### PR TITLE
```frogfs_vfs_open``` multithreading fix for VFS

### LINKED ISSUE #72: Thread safety issue
Hi!

I would just like to ask if FrogFS is thread-safe?
I am debugging some crashes on my ESP32-P4 project and I managed to reproduce them when trying to read two files from separate threads on ESP-IDFs FreeRTOS.

Best regards,
Norbert

### PR DESCRIPTION
**Pull request by nkp123**
This fixes #72 . As this is a read-only filesystem I believe there should not be other issues.

### CODE REVIEW

File: src/vfs.c [hunk 1]
```diff
@@ -13,9 +13,11 @@
 #include "esp_err.h"
 #include "esp_vfs.h"
 
+#include "freertos/idf_additions.h"
```
Comment (jkent) [inline src/vfs.c:16]: The standard includes for FreeRTOS would be:

```c
#include "freertos/FreeRTOS.h"
#include "freertos/semphr.h"
```

File: src/vfs.c [hunk 2]
```diff
@@ -13,9 +13,11 @@
...
 #include "frogfs_config.h"
 #include "frogfs/vfs.h"
 #include "frogfs/frogfs.h"
+#include "portmacro.h"
```
Comment (jkent) [inline src/vfs.c:20]: This is not needed with the above change.

File: src/vfs.c [hunk 3]
```diff
@@ -108,6 +111,15 @@ static int frogfs_vfs_open(void *ctx, const char *path, int flags, int mode)
...
 }
 
+static int frogfs_vfs_open(void *ctx, const char *path, int flags, int mode)
+{
+    frogfs_vfs_t *vfs = (frogfs_vfs_t *) ctx;
+	xSemaphoreTake(vfs->fh_sem, portMAX_DELAY);
+	int res = frogfs_vfs_open_unsafe(ctx, path, flags, mode);
+	xSemaphoreGive(vfs->fh_sem);
+	return res;
+}
```
Comment (jkent) [inline src/vfs.c:121]: I don't think we need a safe and unsafe api. FreeRTOS is pretty much promised with IDF. I see no harm on keeping the new version as frogfs_vfs_open.  Please combine functionality

**Review by jkent — CHANGES_REQUESTED** [review]
Please see review comments.  I've got a couple of changes I'd like to see.  Thanks again, Norbert!

File: src/vfs.c (hunk 3 above)
Comment (jkent) [reply src/vfs.c:121]: Sorry, I had to update my comment to clarify.

Comment (jkent) [reply src/vfs.c:121]: I didn't expand the function to look at it, I apologize.  I was a bit rushed when I looked over the changes.  I understand now that it would produce messy code, and the unsafe wrapper is actually good form.

**Comment by jkent** [comment]
Sorry for the noise, I took care of this myself.

**Comment by nkp123** [comment]
Hi,
Sorry for late response, I wasn't able to properly test the code to make a new commit. Thanks for taking care of that!

Best regards,
Norbert Pietrucha-Kacprowicz
